### ISSUE TITLE
MCQ vs SCQ is confusing.

### ISSUE THREAD

**Issue by arshabh-copods** [copods/kela-quiz#195]
Let users pick one or more right choices. If the user picks multiple options - it becomes a Multiple Answers Questions or otherwise Single Answer Question

**Comment by anuragP04** [comment]
While creating a question, the user will only see 2 options in the question type dropdown: MCQ and Text. By default, MCQ will be selected.

At bottom of the answer based on user selection, the user will see a note: 'This is MCQ || This is MSQ'.

While creating question entry in DB we will check number of option based on which user will set it is single choice or multiple choice
