### ISSUE TITLE
Need a way to modify existing questions-design

### ISSUE THREAD

**Issue by arshabh-copods** [copods/kela-quiz#196]
https://www.figma.com/file/VxdEoi8fC4FtAj7T78EnZe/Quiz?node-id=1%3A1500&t=ExuNU3eUB3M5CKs5-0

**Comment by yashwants64** [comment]
designs: https://www.figma.com/file/VxdEoi8fC4FtAj7T78EnZe/Quiz?node-id=4316%3A5289&t=aF89vqtPJlwqOZgs-4
