### ISSUE TITLE
Detailed result page design

### ISSUE THREAD

**Issue by anuragP04** [copods/kela-quiz#342]
In result of candidate, show question with respective answer that candidate has given for each section

https://www.figma.com/file/VxdEoi8fC4FtAj7T78EnZe/Quiz?node-id=4317%3A5298&t=1iEug1M8Bi63fpP5-0

**Comment by yashwants64** [comment]
updated designs: 
[](https://www.figma.com/file/VxdEoi8fC4FtAj7T78EnZe/Quiz?node-id=4317%3A5298&t=aF89vqtPJlwqOZgs-4)
