### ISSUE TITLE
add accessibility check using eslint

### ISSUE THREAD

**Issue by arshabh-copods** [copods/kela-quiz#49]
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y

**Comment by arshabh-copods** [comment]
@richa-copods What is the status of this issue ? Is someone working on this ?

**Comment by richa-copods** [comment]
> @richa-copods What is the status of this issue ? Is someone working on this ?

@Dhruv-Copods has worked on it and @anuragP04 has reviewed it.
