### ISSUE TITLE
Explore how can we integrate the feature of writing code

### ISSUE THREAD

**Issue by anuragP04** [copods/kela-quiz#503]
1. Just writing code will be enough or should also give the feature of running the written code
2. Which code editor to integrate and evaluation criteria
3. Show preview of written code on Results Page

**Comment by zia-copods** [comment]
I was looking into this issue on how to build a code execution system. My initial thought was we have 3 options

1. Using WASM.
2. Using a SAAS service.
3. We can do it ourselves.

The first two options were not best in our interest as we have limited resources/bandwidth and funds to expend over WASM or SAAS service.

I was looking for the third option on how we can do this in the best way possible and can build over it in the future. I came across a framework named `Judge0` which is a SAAS service but we can use its CE version for our purpose. I have looked at its [Github repo](https://github.com/judge0/judge0) and saw some promising stats. 

In my opinion, `Judge0` can fulfill our technical needs along with UI libraries(Code Editor). I have linked some resources for a better understanding of the framework.

[FreeCodeCamp Blog](https://www.freecodecamp.org/news/how-to-build-react-based-code-editor/)


**Note on WASM**: WASM is quite good but we don't have enough Bandwidth to build our own system from scratch and maintain it for the long run.
