### ISSUE TITLE
Result Tab: redirection glitch

### ISSUE THREAD

**Issue by anuragP04** [copods/kela-quiz#600]
Steps to reproduce:
Step1: Visit Result Page
Step 2: click on `Results` menu on sidebar, 

You will observe the list that is fetching is changing because of filter

**Comment by ayushicopods** [comment]
The issue is Already resolved

[](url)

![Image](https://user-images.githubusercontent.com/107034412/218430909-9e21d68e-c8c5-48c0-aabf-d91ab266f13e.gif)
