### ISSUE TITLE
[Role Based Access Control]: Create a feature branch and add permissions objects and functions

### ISSUE THREAD

**Issue by richa-copods** [copods/kela-quiz#709]
1. Fork the branch for work from "feature/role-based-access-control-main"
2. Create a feature branch
3. Create the Permissions Object based on Roles
4. Create the function to validate the role for a particular feature. (Should return true if particular role can access the particular feature else false)

Please refer the image to know the accessible features for different Roles:

![Image](https://user-images.githubusercontent.com/110384251/221158257-d2ca3c27-eb85-4a4d-ba0d-585826d50db3.png)

**Comment by anuragP04** [comment]
![Image](https://user-images.githubusercontent.com/106807559/221811740-9e90a001-828a-4d44-b084-86213c3266c6.png)
