### ISSUE TITLE
Create a spreadsheet for secrets

### ISSUE THREAD

**Issue by arshabh-copods** [copods/kela-quiz#83]
Create a share only secrets google spreadsheet. 
Create 3 tabs - dev, staging, prod and write down appropriate secrets in it.
Mention this link in the the secrets readme file.

**Comment by anuragP04** [comment]
https://docs.google.com/spreadsheets/d/1QHtxVvBboDRcMuR0ZIql-xSZxiwj9oNqRItVR0fx0hA/edit#gid=0
